### ISSUE TITLE
como usuario quiero ver los derechos de autor para saber que todo esta bajo el marco legal 

### ISSUE THREAD

**Issue by monicacalle** [jucemalco/theFinalProject#51]
criterios de aceptacion

- [ ] el footer debe ser visible en todas las vistas 
- [ ] el footer debe tener el nombre de la pagina al lado izuierdo
- [ ] el footer debe tener los accesos a las RRSS de la pagina 
- [ ] el footer debe tener los copyrights al lado derecho
